### ISSUE TITLE
Support for lat/long

### ISSUE THREAD

**Issue by mneznanski** [datanews/locator#12]
We're often needing to locate places and events that don't have street addresses (wildfires, closures in rural areas). Adding support for lat/long in the address field would be helpful.

**Comment by zzolo** [comment]
![screen shot 2016-08-10 at 9 03 03 pm](https://cloud.githubusercontent.com/assets/190733/17576944/e696312c-5f3d-11e6-96c0-ad42a76ffb15.png)

This actually works "out of the box" with the Google Maps geocoder.

**Comment by zzolo** [comment]
Oh, will add a bit of text to help with this, though.

**Comment by mneznanski** [comment]
Awesome. Thanks!
