### ISSUE TITLE
Allow highlighting of NYC buildings

### ISSUE THREAD

**Issue by veltman** [datanews/locator#6]
This would probably entail clicking on a point, and then querying the NYC geocoder for the pluto shape of the building on it.

A non-NYC specific version would probably be possible using Mapzen or some other OSM querying layer in between.

Either one seems very hard.

**Comment by zzolo** [comment]
I feel like this can be handled by the drawing functionality.  But, if the desire is to outline many buildings, drawing, may be too much.
